# Generated by Django 4.2.16 on 2024-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookorder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookorder",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
