# Generated by Django 4.2.16 on 2024-11-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table="book_inventory",
        ),
    ]
