# Generated by Django 4.2.16 on 2024-11-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table=None,
        ),
    ]
