# Generated by Django 4.2.16 on 2024-11-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_book_prices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="prices",
        ),
    ]
